### ISSUE TITLE
Don't put your curlies on a new line, that's disgusting

### ISSUE THREAD

**Issue by ghost** [alexmat2on/rot64-cipher#1]
https://github.com/alexmat2on/rot64-cipher/blob/3f6614a6ed1ca68cca81ff8a4180a0eca568d142/rot64.cpp#L63

**Comment by alexmat2on** [comment]
it's an issue with [upstream](https://github.com/ReneNyffenegger/cpp-base64/blob/master/base64.cpp#L67)
